### ISSUE TITLE
./f home Problem.

### ISSUE THREAD

**Issue by clerkk** [drtshock/HCFProblems#132]
org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-1646]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[spigot.jar:git-Spigot-1646]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) ~[spigot.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1043) [spigot.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:880) [spigot.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [spigot.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [spigot.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [spigot.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1646]
Caused by: java.lang.NoSuchMethodError: com.earth2me.essentials.IEssentials.getUser(Lorg/bukkit/entity/Player;)Lcom/earth2me/essentials/User;
	at com.massivecraft.factions.integration.Essentials.isVanished(Essentials.java:59) ~[?:?]
	at com.massivecraft.factions.zcore.persist.MemoryFPlayer.isVanished(MemoryFPlayer.java:145) ~[?:?]
	at com.massivecraft.factions.cmd.CmdHome.perform(CmdHome.java:83) ~[?:?]
	at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:123) ~[?:?]
	at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:50) ~[?:?]
	at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:109) ~[?:?]
	at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:50) ~[?:?]
	at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:127) ~[?:?]
	at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:296) ~[?:?]
	at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:259) ~[?:?]
	at com.massivecraft.factions.P.handleCommand(P.java:185) ~[?:?]
	at com.massivecraft.factions.P.onCommand(P.java:197) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-1646]
	... 13 more
[15:51:24]

Player are not able to /f home & this is on the latest version of Factions.

**Comment by nsporillo** [comment]
Do you have essentials installed as a plugin? What version of essentials are you using?

**Comment by clerkk** [comment]
We have essentials & its not working on this version:
https://hub.spigotmc.org/jenkins/job/Spigot-Essentials/

**Comment by Quizzes** [comment]
@clerkk Set the teleport delay in Essentials config.yml

<code>teleport-delay: 1

That would make it one second.

**Comment by clerkk** [comment]
That makes no difference @Quizzes

**Comment by nsporillo** [comment]
@clerkk try finding a different version of essentials, it appears to just be an issue with that. All we're doing is checking if a player is vanished, the error is sourced from the version of essentials you're using (the method we use isnt found).
