### ISSUE TITLE
Bug on /f show (Internal Error)

### ISSUE THREAD

**Issue by IlPicasso** [drtshock/HCFProblems#270]
Hello I just purchased the plugin and while I was testing it  I got this error on /f show

[23:37:58] [Server thread/INFO]: KevinKinGamer issued server command: /f desc Vatos Locos
[23:37:59] [Async Chat Thread - #3/INFO]: - <TheEstebanGames> invitame
[23:38:01] [Server thread/INFO]: KevinKinGamer issued server command: /f invite TheEstebanGames
[23:38:08] [Server thread/INFO]: TheEstebanGames issued server command: /f join SoupsKidz
[23:38:08] [Server thread/INFO]: [Factions v0.0.7-b44] TheEstebanGames joined the faction SoupsKidz.
[23:38:10] [Async Chat Thread - #3/INFO]: SoupsKidz <TheEstebanGames> asd
[23:38:16] [Server thread/INFO]: Il_Picasso issued server command: /f enemy SoupsKidz
[23:38:24] [Server thread/INFO]: Il_Picasso issued server command: /f ally
[23:38:26] [Async Chat Thread - #3/INFO]: SoupsKidz <TheEstebanGames> lelel
[23:38:30] [Async Chat Thread - #3/INFO]: SoupsKidz <TheEstebanGames> esta op
[23:38:34] [Server thread/INFO]: Il_Picasso issued server command: /f show
[23:38:34] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'f' in plugin Factions v0.0.7-b44
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-c136710-350cb99]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-c136710-350cb99]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot.jar:git-Spigot-c136710-350cb99]
	at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1133) [spigot.jar:git-Spigot-c136710-350cb99]
	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968) [spigot.jar:git-Spigot-c136710-350cb99]
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-c136710-350cb99]
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-c136710-350cb99]
	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-c136710-350cb99]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_75]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_75]
	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot.jar:git-Spigot-c136710-350cb99]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot.jar:git-Spigot-c136710-350cb99]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-c136710-350cb99]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-c136710-350cb99]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-c136710-350cb99]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
Caused by: java.lang.UnsupportedOperationException: SuperPerms no group permissions.
	at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPrimaryGroup(Permission_SuperPerms.java:96) ~[?:?]
	at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:726) ~[?:?]
	at com.massivecraft.factions.P.getPrimaryGroup(P.java:322) ~[?:?]
	at com.massivecraft.factions.zcore.util.TagReplacer.getValue(TagReplacer.java:146) ~[?:?]
	at com.massivecraft.factions.zcore.util.TagUtil.parsePlain(TagUtil.java:48) ~[?:?]
	at com.massivecraft.factions.zcore.util.TagUtil.tipPlayer(TagUtil.java:218) ~[?:?]
	at com.massivecraft.factions.zcore.util.TagUtil.getFancy(TagUtil.java:161) ~[?:?]
	at com.massivecraft.factions.zcore.util.TagUtil.parseFancy(TagUtil.java:83) ~[?:?]
	at com.massivecraft.factions.cmd.CmdShow.perform(CmdShow.java:64) ~[?:?]
	at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:123) ~[?:?]
	at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:50) ~[?:?]
	at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:109) ~[?:?]
	at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:50) ~[?:?]
	at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:127) ~[?:?]
	at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:296) ~[?:?]
	at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:259) ~[?:?]
	at com.massivecraft.factions.P.handleCommand(P.java:185) ~[?:?]
	at com.massivecraft.factions.P.onCommand(P.java:197) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-c136710-350cb99]
	... 15 more
[23:38:36] [Server thread/INFO]: Il_Picasso issued server command: /f show
[23:38:36] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'f' in plugin Factions v0.0.7-b44
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-c136710-350cb99]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-c136710-350cb99]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot.jar:git-Spigot-c136710-350cb99]
	at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1133) [spigot.jar:git-Spigot-c136710-350cb99]
	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968) [spigot.jar:git-Spigot-c136710-350cb99]
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-c136710-350cb99]
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-c136710-350cb99]
	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-c136710-350cb99]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_75]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_75]
	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot.jar:git-Spigot-c136710-350cb99]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot.jar:git-Spigot-c136710-350cb99]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-c136710-350cb99]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-c136710-350cb99]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-c136710-350cb99]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
Caused by: java.lang.UnsupportedOperationException: SuperPerms no group permissions.
	at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPrimaryGroup(Permission_SuperPerms.java:96) ~[?:?]
	at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:726) ~[?:?]
	at com.massivecraft.factions.P.getPrimaryGroup(P.java:322) ~[?:?]
	at com.massivecraft.factions.zcore.util.TagReplacer.getValue(TagReplacer.java:146) ~[?:?]
	at com.massivecraft.factions.zcore.util.TagUtil.parsePlain(TagUtil.java:48) ~[?:?]
	at com.massivecraft.factions.zcore.util.TagUtil.tipPlayer(TagUtil.java:218) ~[?:?]
	at com.massivecraft.factions.zcore.util.TagUtil.getFancy(TagUtil.java:161) ~[?:?]
	at com.massivecraft.factions.zcore.util.TagUtil.parseFancy(TagUtil.java:83) ~[?:?]
	at com.massivecraft.factions.cmd.CmdShow.perform(CmdShow.java:64) ~[?:?]
	at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:123) ~[?:?]
	at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:50) ~[?:?]
	at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:109) ~[?:?]
	at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:50) ~[?:?]
	at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:127) ~[?:?]
	at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:296) ~[?:?]
	at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:259) ~[?:?]
	at com.massivecraft.factions.P.handleCommand(P.java:185) ~[?:?]
	at com.massivecraft.factions.P.onCommand(P.java:197) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-c136710-350cb99]
	... 15 more
[23:38:39] [Server thread/INFO]: KevinKinGamer issued server command: /tp Il_Picasso
[23:38:52] [Server thread/INFO]: KevinKinGamer issued server command: /kill TheEstebanGames
[23:38:58] [Server thread/INFO]: TheEstebanGames issued server command: /back
[23:38:59] [Server thread/INFO]: Il_Picasso issued server command: /f show
[23:38:59] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'f' in plugin Factions v0.0.7-b44
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-c136710-350cb99]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-c136710-350cb99]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot.jar:git-Spigot-c136710-350cb99]
	at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1133) [spigot.jar:git-Spigot-c136710-350cb99]
	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968) [spigot.jar:git-Spigot-c136710-350cb99]
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-c136710-350cb99]
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-c136710-350cb99]
	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-c136710-350cb99]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_75]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_75]
	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot.jar:git-Spigot-c136710-350cb99]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot.jar:git-Spigot-c136710-350cb99]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-c136710-350cb99]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-c136710-350cb99]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-c136710-350cb99]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
Caused by: java.lang.UnsupportedOperationException: SuperPerms no group permissions.
	at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPrimaryGroup(Permission_SuperPerms.java:96) ~[?:?]
	at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:726) ~[?:?]
	at com.massivecraft.factions.P.getPrimaryGroup(P.java:322) ~[?:?]
	at com.massivecraft.factions.zcore.util.TagReplacer.getValue(TagReplacer.java:146) ~[?:?]
	at com.massivecraft.factions.zcore.util.TagUtil.parsePlain(TagUtil.java:48) ~[?:?]
	at com.massivecraft.factions.zcore.util.TagUtil.tipPlayer(TagUtil.java:218) ~[?:?]
	at com.massivecraft.factions.zcore.util.TagUtil.getFancy(TagUtil.java:161) ~[?:?]
	at com.massivecraft.factions.zcore.util.TagUtil.parseFancy(TagUtil.java:83) ~[?:?]
	at com.massivecraft.factions.cmd.CmdShow.perform(CmdShow.java:64) ~[?:?]
	at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:123) ~[?:?]
	at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:50) ~[?:?]
	at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:109) ~[?:?]
	at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:50) ~[?:?]
	at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:127) ~[?:?]
	at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:296) ~[?:?]
	at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:259) ~[?:?]
	at com.massivecraft.factions.P.handleCommand(P.java:185) ~[?:?]
	at com.massivecraft.factions.P.onCommand(P.java:197) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-c136710-350cb99]
	... 15 more
[23:38:59] [Netty Epoll Server IO #0/INFO]: UUID of player Jooo

and looks like this

Also seems to be an error with permissions

I use SQLPerms

**Comment by AlfieC** [comment]
Read your error message. Your group has no permissions.

**Comment by nsporillo** [comment]
^ This is not a bug with /f show it is a problem with your permissions. You can go into tooltips and remove the line which displays the users group if you don't know how or don't want to fix permissions.
