### ISSUE TITLE
Please implement isNone() method on com.massivecraft.factions.Faction

### ISSUE THREAD

**Issue by jmcmullen** [drtshock/HCFProblems#368]
FBasics works as intended with FactionsUUID however as soon as HCFactions is added into the mix it stops working and generates the below error.
```
[02:50:13] [Server thread/INFO]: Neekzorz issued server command: /wild
[02:50:13] [Craft Scheduler Thread - 17/WARN]: Exception in thread "Craft Scheduler Thread - 17" 
[02:50:13] [Craft Scheduler Thread - 17/WARN]: org.apache.commons.lang.UnhandledException: Plugin FBasics v2.0.9 generated an exception while executing task 157
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: com.massivecraft.factions.Faction.isNone()Z
	at org.originmc.fbasics.factions.v1_6.FactionsHook.isWilderness(FactionsHook.java:20)
	at org.originmc.fbasics.task.WildernessFactionsTask.run(WildernessFactionsTask.java:24)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more
 ```

**Comment by lol768** [comment]
FactionsUUID implementation: https://github.com/drtshock/Factions/blob/1.6.x/src/main/java/com/massivecraft/factions/zcore/persist/MemoryFaction.java#L359

**Comment by nsporillo** [comment]
I believe the name of the function was changed semi recently. So I can add a compatibility method to fix this issue. 

However I'm at work until 5, so when I get back I'll add this. Thanks for the report.

**Comment by jmcmullen** [comment]
No rush mate, thanks for the quick reply :+1:

**Comment by nsporillo** [comment]
@jmcmullen should be fixed as of build 66.
