### ISSUE TITLE
Error with /f who

### ISSUE THREAD

**Issue by ZeSteRy** [drtshock/HCFProblems#407]
[14:27:15 INFO]: ZeSteRy issued server command: /f who
[14:27:15 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'f' in plugin Factions v0.0.7-b63
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[hcf.jar:git-PaperSpigot-43]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[hcf.jar:git-PaperSpigot-43]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:766) ~[hcf.jar:git-PaperSpigot-43]
        at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1044) [hcf.jar:git-PaperSpigot-43]
        at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:881) [hcf.jar:git-PaperSpigot-43]
        at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [hcf.jar:git-PaperSpigot-43]
        at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [hcf.jar:git-PaperSpigot-43]
        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:189) [hcf.jar:git-PaperSpigot-43]
        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [hcf.jar:git-PaperSpigot-43]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:789) [hcf.jar:git-PaperSpigot-43]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:307) [hcf.jar:git-PaperSpigot-43]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:638) [hcf.jar:git-PaperSpigot-43]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:544) [hcf.jar:git-PaperSpigot-43]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [hcf.jar:git-PaperSpigot-43]
Caused by: java.lang.UnsupportedOperationException: SuperPerms no group permissions.
        at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPrimaryGroup(Permission_SuperPerms.java:96) ~[?:?]
        at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:726) ~[?:?]
        at com.massivecraft.factions.P.getPrimaryGroup(P.java:322) ~[?:?]
        at com.massivecraft.factions.zcore.util.TagReplacer.getValue(TagReplacer.java:169) ~[?:?]
        at com.massivecraft.factions.zcore.util.TagUtil.parsePlain(TagUtil.java:47) ~[?:?]
        at com.massivecraft.factions.zcore.util.TagUtil.tipPlayer(TagUtil.java:229) ~[?:?]
        at com.massivecraft.factions.zcore.util.TagUtil.getFancy(TagUtil.java:169) ~[?:?]
        at com.massivecraft.factions.zcore.util.TagUtil.parseFancy(TagUtil.java:87) ~[?:?]
        at com.massivecraft.factions.cmd.CmdShow.perform(CmdShow.java:67) ~[?:?]
        at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:123) ~[?:?]
        at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:50) ~[?:?]
        at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:109) ~[?:?]
        at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:50) ~[?:?]
        at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:127) ~[?:?]
        at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:287) ~[?:?]
        at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:250) ~[?:?]
        at com.massivecraft.factions.P.handleCommand(P.java:185) ~[?:?]
        at com.massivecraft.factions.P.onCommand(P.java:197) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[hcf.jar:git-PaperSpigot-43]
        ... 13 more

Thanks

**Comment by drtshock** [comment]
get a permissions plugin
